# --- !Ups

ALTER TABLE REVISIONS ADD reviewStatus INT NOT NULL DEFAULT 0;
ALTER TABLE REVISIONS ADD reviewAuthorID BIGINT;

-- foreign key constraints :
ALTER TABLE REVISIONS ADD CONSTRAINT REVISIONS_FK3 FOREIGN KEY (reviewAuthorID) REFERENCES AUTHORS (id);

# --- !Downs

ALTER TABLE REVISIONS DROP COLUMN reviewStatus;
ALTER TABLE REVISIONS DROP COLUMN reviewAuthorID;